### ISSUE TITLE
Empty tuple expansion generates invalid sql

### ISSUE THREAD

**Issue by Cnoor0171** [cpburnz/python-sqlparams#8]
Hi,
First of all, thanks for the great module.

I noticed that tuple expansion doesn't take into account that empty arrays are not legal in sql. Thus the users need to manually check if the input has zero length. For instance,
```python
import sqlparams
query = sqlparams.SQLParams('named', 'qmark')
sql, params = query.format("SELECT * FROM users WHERE name IN :names", {'names': ()})

print(sql)
```
results in `SELECT * FROM users WHERE name IN ()`, which is not valid sql.

I think in this edge case, the tuple should instead expand to `(NULL)`. Since nothing compares equal to `NULL`, this will always be false, which is the expected behavior. Alternatively, you can always add `NULL` in the beginning of sql arrays, since it doesn't change the behavior. But I think that would result in uglier sql statements in the general case.

**Comment by cpburnz** [comment]
Empty tuples are now expanded to `(NULL)` in v5.0.0.
